#--------------------------------------------------------------
#          Makefile for micromagnetic module
#--------------------------------------------------------------

# List module object filenames
micromagnetic_objects =\
data.o \
initialize.o \
interface.o \
LLG.o \
calculate_fields.o \
steps.o 
# Append module objects to global tree
OBJECTS+=$(addprefix obj/micromagnetic/,$(micromagnetic_objects))
